### ISSUE TITLE
Future Prediction Heatmap

### ISSUE THREAD

**Issue by wmCmo** [Destaq/mochi-heatmap#1]
Why is there a future prediction of my review on Heatmap?😅 Is this an intended feature?
![image](https://github.com/Destaq/mochi-heatmap/assets/51499433/9b4c09e6-623b-42cf-8c73-b4b9aa0cce34)

**Comment by Destaq** [comment]
This is indeed intended. Such behavior emulates that of Anki's heatmap plugin.
